apiVersion: v1
kind: Secret
metadata:
  name: echo-sink-configuration
stringData:
  logLevel: WARN
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: echo-sink-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["echo-sink-configuration"]
  verbs: ["get"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: echo-sink-role-binding
subjects:
- kind: ServiceAccount
  name: my-connect-connect
  namespace: myproject
roleRef:
  kind: Role
  name: echo-sink-role
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: echo-sink-connector
  labels:
    strimzi.io/cluster: my-connect
spec:
  class: EchoSink
  tasksMax: 1
  config:
    level: ${secrets:myproject/echo-sink-configuration:logLevel}
    topics: timer-topic
